%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'QPM_US_20074';
M_.dynare_version = '4.5.7';
oo_.dynare_version = '4.5.7';
options_.dynare_version = '4.5.7';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('QPM_US_20074.log');
M_.exo_names = 'RES_RR_US_BAR';
M_.exo_names_tex = 'RES\_RR\_US\_BAR';
M_.exo_names_long = 'RES_RR_US_BAR';
M_.exo_names = char(M_.exo_names, 'RES_UNR_US_GAP');
M_.exo_names_tex = char(M_.exo_names_tex, 'RES\_UNR\_US\_GAP');
M_.exo_names_long = char(M_.exo_names_long, 'RES_UNR_US_GAP');
M_.exo_names = char(M_.exo_names, 'RES_UNR_US_BAR');
M_.exo_names_tex = char(M_.exo_names_tex, 'RES\_UNR\_US\_BAR');
M_.exo_names_long = char(M_.exo_names_long, 'RES_UNR_US_BAR');
M_.exo_names = char(M_.exo_names, 'RES_RS_US');
M_.exo_names_tex = char(M_.exo_names_tex, 'RES\_RS\_US');
M_.exo_names_long = char(M_.exo_names_long, 'RES_RS_US');
M_.exo_names = char(M_.exo_names, 'RES_G_US');
M_.exo_names_tex = char(M_.exo_names_tex, 'RES\_G\_US');
M_.exo_names_long = char(M_.exo_names_long, 'RES_G_US');
M_.exo_names = char(M_.exo_names, 'RES_Y_US');
M_.exo_names_tex = char(M_.exo_names_tex, 'RES\_Y\_US');
M_.exo_names_long = char(M_.exo_names_long, 'RES_Y_US');
M_.exo_names = char(M_.exo_names, 'RES_LGDP_US_BAR');
M_.exo_names_tex = char(M_.exo_names_tex, 'RES\_LGDP\_US\_BAR');
M_.exo_names_long = char(M_.exo_names_long, 'RES_LGDP_US_BAR');
M_.exo_names = char(M_.exo_names, 'RES_PIE_US');
M_.exo_names_tex = char(M_.exo_names_tex, 'RES\_PIE\_US');
M_.exo_names_long = char(M_.exo_names_long, 'RES_PIE_US');
M_.exo_names = char(M_.exo_names, 'RES_UNR_G_US');
M_.exo_names_tex = char(M_.exo_names_tex, 'RES\_UNR\_G\_US');
M_.exo_names_long = char(M_.exo_names_long, 'RES_UNR_G_US');
M_.exo_names = char(M_.exo_names, 'RES_BLT_US');
M_.exo_names_tex = char(M_.exo_names_tex, 'RES\_BLT\_US');
M_.exo_names_long = char(M_.exo_names_long, 'RES_BLT_US');
M_.exo_names = char(M_.exo_names, 'RES_BLT_US_BAR');
M_.exo_names_tex = char(M_.exo_names_tex, 'RES\_BLT\_US\_BAR');
M_.exo_names_long = char(M_.exo_names_long, 'RES_BLT_US_BAR');
M_.endo_names = 'RR_US';
M_.endo_names_tex = 'RR\_US';
M_.endo_names_long = 'RR_US';
M_.endo_names = char(M_.endo_names, 'RR_US_BAR');
M_.endo_names_tex = char(M_.endo_names_tex, 'RR\_US\_BAR');
M_.endo_names_long = char(M_.endo_names_long, 'RR_US_BAR');
M_.endo_names = char(M_.endo_names, 'UNR_US');
M_.endo_names_tex = char(M_.endo_names_tex, 'UNR\_US');
M_.endo_names_long = char(M_.endo_names_long, 'UNR_US');
M_.endo_names = char(M_.endo_names, 'UNR_US_GAP');
M_.endo_names_tex = char(M_.endo_names_tex, 'UNR\_US\_GAP');
M_.endo_names_long = char(M_.endo_names_long, 'UNR_US_GAP');
M_.endo_names = char(M_.endo_names, 'UNR_US_BAR');
M_.endo_names_tex = char(M_.endo_names_tex, 'UNR\_US\_BAR');
M_.endo_names_long = char(M_.endo_names_long, 'UNR_US_BAR');
M_.endo_names = char(M_.endo_names, 'PIE_US');
M_.endo_names_tex = char(M_.endo_names_tex, 'PIE\_US');
M_.endo_names_long = char(M_.endo_names_long, 'PIE_US');
M_.endo_names = char(M_.endo_names, 'PIE_US4');
M_.endo_names_tex = char(M_.endo_names_tex, 'PIE\_US4');
M_.endo_names_long = char(M_.endo_names_long, 'PIE_US4');
M_.endo_names = char(M_.endo_names, 'Y_US');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y\_US');
M_.endo_names_long = char(M_.endo_names_long, 'Y_US');
M_.endo_names = char(M_.endo_names, 'LGDP_US');
M_.endo_names_tex = char(M_.endo_names_tex, 'LGDP\_US');
M_.endo_names_long = char(M_.endo_names_long, 'LGDP_US');
M_.endo_names = char(M_.endo_names, 'LGDP_US_BAR');
M_.endo_names_tex = char(M_.endo_names_tex, 'LGDP\_US\_BAR');
M_.endo_names_long = char(M_.endo_names_long, 'LGDP_US_BAR');
M_.endo_names = char(M_.endo_names, 'RS_US');
M_.endo_names_tex = char(M_.endo_names_tex, 'RS\_US');
M_.endo_names_long = char(M_.endo_names_long, 'RS_US');
M_.endo_names = char(M_.endo_names, 'G_US');
M_.endo_names_tex = char(M_.endo_names_tex, 'G\_US');
M_.endo_names_long = char(M_.endo_names_long, 'G_US');
M_.endo_names = char(M_.endo_names, 'LCPI_US');
M_.endo_names_tex = char(M_.endo_names_tex, 'LCPI\_US');
M_.endo_names_long = char(M_.endo_names_long, 'LCPI_US');
M_.endo_names = char(M_.endo_names, 'E4_PIE_US4');
M_.endo_names_tex = char(M_.endo_names_tex, 'E4\_PIE\_US4');
M_.endo_names_long = char(M_.endo_names_long, 'E4_PIE_US4');
M_.endo_names = char(M_.endo_names, 'E1_Y_US');
M_.endo_names_tex = char(M_.endo_names_tex, 'E1\_Y\_US');
M_.endo_names_long = char(M_.endo_names_long, 'E1_Y_US');
M_.endo_names = char(M_.endo_names, 'E1_PIE_US');
M_.endo_names_tex = char(M_.endo_names_tex, 'E1\_PIE\_US');
M_.endo_names_long = char(M_.endo_names_long, 'E1_PIE_US');
M_.endo_names = char(M_.endo_names, 'UNR_G_US');
M_.endo_names_tex = char(M_.endo_names_tex, 'UNR\_G\_US');
M_.endo_names_long = char(M_.endo_names_long, 'UNR_G_US');
M_.endo_names = char(M_.endo_names, 'GROWTH_US');
M_.endo_names_tex = char(M_.endo_names_tex, 'GROWTH\_US');
M_.endo_names_long = char(M_.endo_names_long, 'GROWTH_US');
M_.endo_names = char(M_.endo_names, 'GROWTH4_US');
M_.endo_names_tex = char(M_.endo_names_tex, 'GROWTH4\_US');
M_.endo_names_long = char(M_.endo_names_long, 'GROWTH4_US');
M_.endo_names = char(M_.endo_names, 'GROWTH4_US_BAR');
M_.endo_names_tex = char(M_.endo_names_tex, 'GROWTH4\_US\_BAR');
M_.endo_names_long = char(M_.endo_names_long, 'GROWTH4_US_BAR');
M_.endo_names = char(M_.endo_names, 'BLT_US');
M_.endo_names_tex = char(M_.endo_names_tex, 'BLT\_US');
M_.endo_names_long = char(M_.endo_names_long, 'BLT_US');
M_.endo_names = char(M_.endo_names, 'BLT_US_BAR');
M_.endo_names_tex = char(M_.endo_names_tex, 'BLT\_US\_BAR');
M_.endo_names_long = char(M_.endo_names_long, 'BLT_US_BAR');
M_.endo_names = char(M_.endo_names, 'E');
M_.endo_names_tex = char(M_.endo_names_tex, 'E');
M_.endo_names_long = char(M_.endo_names_long, 'E');
M_.endo_names = char(M_.endo_names, 'E2');
M_.endo_names_tex = char(M_.endo_names_tex, 'E2');
M_.endo_names_long = char(M_.endo_names_long, 'E2');
M_.endo_names = char(M_.endo_names, 'GROWTH_US_BAR');
M_.endo_names_tex = char(M_.endo_names_tex, 'GROWTH\_US\_BAR');
M_.endo_names_long = char(M_.endo_names_long, 'GROWTH_US_BAR');
M_.endo_names = char(M_.endo_names, 'RR_US_GAP');
M_.endo_names_tex = char(M_.endo_names_tex, 'RR\_US\_GAP');
M_.endo_names_long = char(M_.endo_names_long, 'RR_US_GAP');
M_.endo_names = char(M_.endo_names, 'BLT_US_GAP');
M_.endo_names_tex = char(M_.endo_names_tex, 'BLT\_US\_GAP');
M_.endo_names_long = char(M_.endo_names_long, 'BLT_US_GAP');
M_.endo_names = char(M_.endo_names, 'rff_q_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'rff\_q\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'rff_q_obs');
M_.endo_names = char(M_.endo_names, 'pgdp_q_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'pgdp\_q\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'pgdp_q_obs');
M_.endo_names = char(M_.endo_names, 'xgdp_q_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'xgdp\_q\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'xgdp_q_obs');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_234');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_234');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_234');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_238');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_238');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_238');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_124');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_124');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_124');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_250');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_250');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_250');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_173');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_173');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_173');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_155');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_155');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_155');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_22_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_22\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_22_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_22_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_22\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_22_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_22_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_22\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_22_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_22_4');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_22\_4');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_22_4');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_22_5');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_22\_5');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_22_5');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_22_6');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_22\_6');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_22_6');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_22_7');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_22\_7');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_22_7');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_22_8');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_22\_8');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_22_8');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_8_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_8\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_8_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_8_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_8\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_8_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_8_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_8\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_8_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_9_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_9\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_9_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_9_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_9\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_9_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_9_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_9\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_9_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_5_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_5\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_5_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_5_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_5\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_5_2');
M_.endo_partitions = struct();
M_.param_names = 'rho_us';
M_.param_names_tex = 'rho\_us';
M_.param_names_long = 'rho_us';
M_.param_names = char(M_.param_names, 'rr_us_bar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'rr\_us\_bar\_ss');
M_.param_names_long = char(M_.param_names_long, 'rr_us_bar_ss');
M_.param_names = char(M_.param_names, 'alpha_us1');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_us1');
M_.param_names_long = char(M_.param_names_long, 'alpha_us1');
M_.param_names = char(M_.param_names, 'alpha_us2');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_us2');
M_.param_names_long = char(M_.param_names_long, 'alpha_us2');
M_.param_names = char(M_.param_names, 'tau_us');
M_.param_names_tex = char(M_.param_names_tex, 'tau\_us');
M_.param_names_long = char(M_.param_names_long, 'tau_us');
M_.param_names = char(M_.param_names, 'growth_us_ss');
M_.param_names_tex = char(M_.param_names_tex, 'growth\_us\_ss');
M_.param_names_long = char(M_.param_names_long, 'growth_us_ss');
M_.param_names = char(M_.param_names, 'beta_us1');
M_.param_names_tex = char(M_.param_names_tex, 'beta\_us1');
M_.param_names_long = char(M_.param_names_long, 'beta_us1');
M_.param_names = char(M_.param_names, 'beta_us2');
M_.param_names_tex = char(M_.param_names_tex, 'beta\_us2');
M_.param_names_long = char(M_.param_names_long, 'beta_us2');
M_.param_names = char(M_.param_names, 'beta_us3');
M_.param_names_tex = char(M_.param_names_tex, 'beta\_us3');
M_.param_names_long = char(M_.param_names_long, 'beta_us3');
M_.param_names = char(M_.param_names, 'lambda_us1');
M_.param_names_tex = char(M_.param_names_tex, 'lambda\_us1');
M_.param_names_long = char(M_.param_names_long, 'lambda_us1');
M_.param_names = char(M_.param_names, 'lambda_us2');
M_.param_names_tex = char(M_.param_names_tex, 'lambda\_us2');
M_.param_names_long = char(M_.param_names_long, 'lambda_us2');
M_.param_names = char(M_.param_names, 'gamma_us1');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_us1');
M_.param_names_long = char(M_.param_names_long, 'gamma_us1');
M_.param_names = char(M_.param_names, 'gamma_us2');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_us2');
M_.param_names_long = char(M_.param_names_long, 'gamma_us2');
M_.param_names = char(M_.param_names, 'gamma_us4');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_us4');
M_.param_names_long = char(M_.param_names_long, 'gamma_us4');
M_.param_names = char(M_.param_names, 'pietar_us_ss');
M_.param_names_tex = char(M_.param_names_tex, 'pietar\_us\_ss');
M_.param_names_long = char(M_.param_names_long, 'pietar_us_ss');
M_.param_names = char(M_.param_names, 'alpha_us3');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_us3');
M_.param_names_long = char(M_.param_names_long, 'alpha_us3');
M_.param_names = char(M_.param_names, 'kappa_us');
M_.param_names_tex = char(M_.param_names_tex, 'kappa\_us');
M_.param_names_long = char(M_.param_names_long, 'kappa_us');
M_.param_names = char(M_.param_names, 'theta');
M_.param_names_tex = char(M_.param_names_tex, 'theta');
M_.param_names_long = char(M_.param_names_long, 'theta');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 11;
M_.endo_nbr = 52;
M_.param_nbr = 18;
M_.orig_endo_nbr = 30;
M_.aux_vars(1).endo_index = 31;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 32;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 33;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 34;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 35;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 36;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 37;
M_.aux_vars(7).type = 1;
M_.aux_vars(7).orig_index = 23;
M_.aux_vars(7).orig_lead_lag = -1;
M_.aux_vars(8).endo_index = 38;
M_.aux_vars(8).type = 1;
M_.aux_vars(8).orig_index = 23;
M_.aux_vars(8).orig_lead_lag = -2;
M_.aux_vars(9).endo_index = 39;
M_.aux_vars(9).type = 1;
M_.aux_vars(9).orig_index = 23;
M_.aux_vars(9).orig_lead_lag = -3;
M_.aux_vars(10).endo_index = 40;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 23;
M_.aux_vars(10).orig_lead_lag = -4;
M_.aux_vars(11).endo_index = 41;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 23;
M_.aux_vars(11).orig_lead_lag = -5;
M_.aux_vars(12).endo_index = 42;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 23;
M_.aux_vars(12).orig_lead_lag = -6;
M_.aux_vars(13).endo_index = 43;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 23;
M_.aux_vars(13).orig_lead_lag = -7;
M_.aux_vars(14).endo_index = 44;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 23;
M_.aux_vars(14).orig_lead_lag = -8;
M_.aux_vars(15).endo_index = 45;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 9;
M_.aux_vars(15).orig_lead_lag = -1;
M_.aux_vars(16).endo_index = 46;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 9;
M_.aux_vars(16).orig_lead_lag = -2;
M_.aux_vars(17).endo_index = 47;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 9;
M_.aux_vars(17).orig_lead_lag = -3;
M_.aux_vars(18).endo_index = 48;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 10;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(19).endo_index = 49;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 10;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(20).endo_index = 50;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 10;
M_.aux_vars(20).orig_lead_lag = -3;
M_.aux_vars(21).endo_index = 51;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 6;
M_.aux_vars(21).orig_lead_lag = -1;
M_.aux_vars(22).endo_index = 52;
M_.aux_vars(22).type = 1;
M_.aux_vars(22).orig_index = 6;
M_.aux_vars(22).orig_lead_lag = -2;
options_.varobs = cell(1);
options_.varobs(1)  = {'UNR_US'};
options_.varobs(2)  = {'RS_US'};
options_.varobs(3)  = {'LCPI_US'};
options_.varobs(4)  = {'LGDP_US'};
options_.varobs(5)  = {'BLT_US'};
options_.varobs_id = [ 3 11 13 9 21  ];
M_.Sigma_e = zeros(11, 11);
M_.Correlation_matrix = eye(11, 11);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('QPM_US_20074_static');
erase_compiled_function('QPM_US_20074_dynamic');
M_.orig_eq_nbr = 30;
M_.eq_nbr = 52;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 1 32 0;
 2 33 0;
 0 34 0;
 3 35 0;
 4 36 0;
 5 37 84;
 6 38 85;
 7 39 86;
 8 40 0;
 9 41 0;
 10 42 0;
 11 43 0;
 12 44 0;
 0 45 0;
 0 46 0;
 0 47 0;
 13 48 0;
 0 49 0;
 0 50 0;
 0 51 0;
 0 52 0;
 14 53 0;
 15 54 0;
 0 55 0;
 0 56 0;
 0 57 0;
 0 58 0;
 0 59 0;
 0 60 0;
 0 61 0;
 0 62 87;
 0 63 88;
 0 64 89;
 0 65 90;
 0 66 91;
 0 67 92;
 16 68 0;
 17 69 0;
 18 70 0;
 19 71 0;
 20 72 0;
 21 73 0;
 22 74 0;
 23 75 0;
 24 76 0;
 25 77 0;
 26 78 0;
 27 79 0;
 28 80 0;
 29 81 0;
 30 82 0;
 31 83 0;]';
M_.nstatic = 15;
M_.nfwrd   = 6;
M_.npred   = 28;
M_.nboth   = 3;
M_.nsfwrd   = 9;
M_.nspred   = 31;
M_.ndynamic   = 37;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:11];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(52, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(11, 1);
M_.params = NaN(18, 1);
M_.NNZDerivatives = [158; 0; -1];
M_.params( 3 ) = 0.7796;
alpha_us1 = M_.params( 3 );
M_.params( 4 ) = 0.1874;
alpha_us2 = M_.params( 4 );
M_.params( 16 ) = 0.3352;
alpha_us3 = M_.params( 16 );
M_.params( 1 ) = 0.9;
rho_us = M_.params( 1 );
M_.params( 2 ) = 1.8456;
rr_us_bar_ss = M_.params( 2 );
M_.params( 5 ) = 0.10;
tau_us = M_.params( 5 );
M_.params( 6 ) = 2.7599;
growth_us_ss = M_.params( 6 );
M_.params( 7 ) = 0.9223;
beta_us1 = M_.params( 7 );
M_.params( 8 ) = 0.1198;
beta_us2 = M_.params( 8 );
M_.params( 9 ) = 0.1300;
beta_us3 = M_.params( 9 );
M_.params( 10 ) = 0.6380;
lambda_us1 = M_.params( 10 );
M_.params( 11 ) = 0.1948;
lambda_us2 = M_.params( 11 );
M_.params( 12 ) = 0.8318;
gamma_us1 = M_.params( 12 );
M_.params( 13 ) = 1.8091;
gamma_us2 = M_.params( 13 );
M_.params( 14 ) = 0.5332;
gamma_us4 = M_.params( 14 );
M_.params( 15 ) = 2.5;
pietar_us_ss = M_.params( 15 );
M_.params( 17 ) = 20.0890;
kappa_us = M_.params( 17 );
M_.params( 18 ) = 1;
theta = M_.params( 18 );
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.1)^2;
M_.Sigma_e(2, 2) = (0.2)^2;
M_.Sigma_e(3, 3) = (0.10)^2;
M_.Sigma_e(4, 4) = (0.7)^2;
M_.Sigma_e(5, 5) = (0.10)^2;
M_.Sigma_e(6, 6) = (0.25)^2;
M_.Sigma_e(7, 7) = (0.05)^2;
M_.Sigma_e(8, 8) = (0.7)^2;
M_.Sigma_e(9, 9) = (0.10)^2;
M_.Sigma_e(10, 10) = (0.4)^2;
M_.Sigma_e(11, 11) = (0.2)^2;
M_.Sigma_e(6, 5) = 0.0025;
M_.Sigma_e(5, 6) = M_.Sigma_e(6, 5);
M_.Sigma_e(7, 8) = 0.003500000000000001;
M_.Sigma_e(8, 7) = M_.Sigma_e(7, 8);
M_.sigma_e_is_diagonal = 0;
options_.diffuse_filter = 1;
options_.steadystate.nocheck = 1;
steady;
oo_.dr.eigval = check(M_,options_,oo_);
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.param_vals = [estim_params_.param_vals; 3, NaN, (-Inf), Inf, 1, 0.8, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 4, NaN, (-Inf), Inf, 2, 0.3, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 16, NaN, (-Inf), Inf, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 6, NaN, (-Inf), Inf, 3, 2.5, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 2, NaN, (-Inf), Inf, 3, 2.0, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 1, NaN, (-Inf), Inf, 1, 0.9, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 5, NaN, (-Inf), Inf, 1, 0.1, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 7, NaN, (-Inf), Inf, 2, 0.75, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 8, NaN, (-Inf), Inf, 1, 0.15, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 9, NaN, (-Inf), Inf, 2, 0.20, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 10, NaN, (-Inf), Inf, 1, 0.50, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 11, NaN, (-Inf), Inf, 2, 0.25, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 12, NaN, (-Inf), Inf, 1, 0.5, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 13, NaN, (-Inf), Inf, 2, 0.50, 0.30, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 14, NaN, (-Inf), Inf, 2, 0.20, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 17, NaN, (-Inf), Inf, 2, 20, 0.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 18, NaN, (-Inf), Inf, 2, 1, 0.5, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, NaN, (-Inf), Inf, 4, 0.2, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, NaN, (-Inf), Inf, 4, 0.1, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 9, NaN, (-Inf), Inf, 4, 0.10, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, NaN, (-Inf), Inf, 4, 0.25, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, NaN, (-Inf), Inf, 4, 0.05, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, NaN, (-Inf), Inf, 4, 0.10, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 8, NaN, (-Inf), Inf, 4, 0.7, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, NaN, (-Inf), Inf, 4, 0.7, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, NaN, (-Inf), Inf, 4, 0.2, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 10, NaN, (-Inf), Inf, 4, 0.4, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 11, NaN, (-Inf), Inf, 4, 0.2, Inf, NaN, NaN, NaN ];
estim_params_.corrx = [estim_params_.corrx; 6, 5, NaN, (-Inf), Inf, 1, 0.25, 0.1, NaN, NaN, NaN ];
estim_params_.corrx = [estim_params_.corrx; 7, 8, NaN, (-Inf), Inf, 1, 0.05, 0.02, NaN, NaN, NaN ];
options_.trend_coeff = {};
tmp1 = strmatch('LCPI_US',options_.varobs,'exact');
options_.trend_coeffs{tmp1} = 'M_.params(15)/4';
tmp1 = strmatch('LGDP_US',options_.varobs,'exact');
options_.trend_coeffs{tmp1} = 'M_.params(6)/4';
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(4, 4) = (M_.params(15)+1.8201)^2;
save('QPM_US_20074_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('QPM_US_20074_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('QPM_US_20074_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('QPM_US_20074_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('QPM_US_20074_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('QPM_US_20074_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('QPM_US_20074_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
disp('Note: 1 warning(s) encountered in the preprocessor')
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
