%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'US_SW07_20074';
M_.dynare_version = '4.5.6';
oo_.dynare_version = '4.5.6';
options_.dynare_version = '4.5.6';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('US_SW07_20074.log');
M_.exo_names = 'z_sh';
M_.exo_names_tex = '\epsilon^z';
M_.exo_names_long = 'z_sh';
M_.exo_names = char(M_.exo_names, 'g_sh');
M_.exo_names_tex = char(M_.exo_names_tex, '\epsilon^g');
M_.exo_names_long = char(M_.exo_names_long, 'g_sh');
M_.exo_names = char(M_.exo_names, 'b_sh');
M_.exo_names_tex = char(M_.exo_names_tex, '\epsilon^b');
M_.exo_names_long = char(M_.exo_names_long, 'b_sh');
M_.exo_names = char(M_.exo_names, 'mu_sh');
M_.exo_names_tex = char(M_.exo_names_tex, '\epsilon^{\mu}');
M_.exo_names_long = char(M_.exo_names_long, 'mu_sh');
M_.exo_names = char(M_.exo_names, 'laf_sh');
M_.exo_names_tex = char(M_.exo_names_tex, '\epsilon^{\lambda_f}');
M_.exo_names_long = char(M_.exo_names_long, 'laf_sh');
M_.exo_names = char(M_.exo_names, 'law_sh');
M_.exo_names_tex = char(M_.exo_names_tex, '\epsilon^{\lambda_w}');
M_.exo_names_long = char(M_.exo_names_long, 'law_sh');
M_.exo_names = char(M_.exo_names, 'rm_sh');
M_.exo_names_tex = char(M_.exo_names_tex, '\epsilon^{r}');
M_.exo_names_long = char(M_.exo_names_long, 'rm_sh');
M_.endo_names = 'y_t';
M_.endo_names_tex = '\hat{y}';
M_.endo_names_long = 'y_t';
M_.endo_names = char(M_.endo_names, 'c_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{c}');
M_.endo_names_long = char(M_.endo_names_long, 'c_t');
M_.endo_names = char(M_.endo_names, 'i_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{i}');
M_.endo_names_long = char(M_.endo_names_long, 'i_t');
M_.endo_names = char(M_.endo_names, 'k_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{k}');
M_.endo_names_long = char(M_.endo_names_long, 'k_t');
M_.endo_names = char(M_.endo_names, 'kbar_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{\bar{k}}');
M_.endo_names_long = char(M_.endo_names_long, 'kbar_t');
M_.endo_names = char(M_.endo_names, 'L_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{L}');
M_.endo_names_long = char(M_.endo_names_long, 'L_t');
M_.endo_names = char(M_.endo_names, 'mc_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{mc}');
M_.endo_names_long = char(M_.endo_names_long, 'mc_t');
M_.endo_names = char(M_.endo_names, 'pi_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{\pi}');
M_.endo_names_long = char(M_.endo_names_long, 'pi_t');
M_.endo_names = char(M_.endo_names, 'R_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{R}');
M_.endo_names_long = char(M_.endo_names_long, 'R_t');
M_.endo_names = char(M_.endo_names, 'rk_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{r}^k');
M_.endo_names_long = char(M_.endo_names_long, 'rk_t');
M_.endo_names = char(M_.endo_names, 'u_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{u}');
M_.endo_names_long = char(M_.endo_names_long, 'u_t');
M_.endo_names = char(M_.endo_names, 'w_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{w}');
M_.endo_names_long = char(M_.endo_names_long, 'w_t');
M_.endo_names = char(M_.endo_names, 'muw_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{mu^w_t}');
M_.endo_names_long = char(M_.endo_names_long, 'muw_t');
M_.endo_names = char(M_.endo_names, 'qk_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{q}^k');
M_.endo_names_long = char(M_.endo_names_long, 'qk_t');
M_.endo_names = char(M_.endo_names, 'z_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{z}');
M_.endo_names_long = char(M_.endo_names_long, 'z_t');
M_.endo_names = char(M_.endo_names, 'ztil_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{\tilde{z}}');
M_.endo_names_long = char(M_.endo_names_long, 'ztil_t');
M_.endo_names = char(M_.endo_names, 'b_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{b}');
M_.endo_names_long = char(M_.endo_names_long, 'b_t');
M_.endo_names = char(M_.endo_names, 'g_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{g}');
M_.endo_names_long = char(M_.endo_names_long, 'g_t');
M_.endo_names = char(M_.endo_names, 'laf_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\tilde{\lambda}^f');
M_.endo_names_long = char(M_.endo_names_long, 'laf_t');
M_.endo_names = char(M_.endo_names, 'law_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\tilde{\lambda}^w');
M_.endo_names_long = char(M_.endo_names_long, 'law_t');
M_.endo_names = char(M_.endo_names, 'mu_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{\mu}');
M_.endo_names_long = char(M_.endo_names_long, 'mu_t');
M_.endo_names = char(M_.endo_names, 'rm_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'r^{m}');
M_.endo_names_long = char(M_.endo_names_long, 'rm_t');
M_.endo_names = char(M_.endo_names, 'xgdp_q_obs');
M_.endo_names_tex = char(M_.endo_names_tex, '\Delta y^{obs}');
M_.endo_names_long = char(M_.endo_names_long, 'xgdp_q_obs');
M_.endo_names = char(M_.endo_names, 'hours_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'L^{obs}');
M_.endo_names_long = char(M_.endo_names_long, 'hours_obs');
M_.endo_names = char(M_.endo_names, 'wage_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'wage^{obs}');
M_.endo_names_long = char(M_.endo_names_long, 'wage_obs');
M_.endo_names = char(M_.endo_names, 'pgdp_q_obs');
M_.endo_names_tex = char(M_.endo_names_tex, '\pi^{obs}');
M_.endo_names_long = char(M_.endo_names_long, 'pgdp_q_obs');
M_.endo_names = char(M_.endo_names, 'rff_q_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'R^{obs}');
M_.endo_names_long = char(M_.endo_names_long, 'rff_q_obs');
M_.endo_names = char(M_.endo_names, 'pcer_q_obs');
M_.endo_names_tex = char(M_.endo_names_tex, '\Delta c^{obs}');
M_.endo_names_long = char(M_.endo_names_long, 'pcer_q_obs');
M_.endo_names = char(M_.endo_names, 'fpi_q_obs');
M_.endo_names_tex = char(M_.endo_names_tex, '\Delta i^{obs}');
M_.endo_names_long = char(M_.endo_names_long, 'fpi_q_obs');
M_.endo_names = char(M_.endo_names, 'y_ft');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{y}^f');
M_.endo_names_long = char(M_.endo_names_long, 'y_ft');
M_.endo_names = char(M_.endo_names, 'c_ft');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{c}^f');
M_.endo_names_long = char(M_.endo_names_long, 'c_ft');
M_.endo_names = char(M_.endo_names, 'i_ft');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{i}^f');
M_.endo_names_long = char(M_.endo_names_long, 'i_ft');
M_.endo_names = char(M_.endo_names, 'k_ft');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{k}^f');
M_.endo_names_long = char(M_.endo_names_long, 'k_ft');
M_.endo_names = char(M_.endo_names, 'kbar_ft');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{\bar{k}}^f');
M_.endo_names_long = char(M_.endo_names_long, 'kbar_ft');
M_.endo_names = char(M_.endo_names, 'L_ft');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{L}^f');
M_.endo_names_long = char(M_.endo_names_long, 'L_ft');
M_.endo_names = char(M_.endo_names, 'r_ft');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{r}^f');
M_.endo_names_long = char(M_.endo_names_long, 'r_ft');
M_.endo_names = char(M_.endo_names, 'rk_ft');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{r}^{f,k}');
M_.endo_names_long = char(M_.endo_names_long, 'rk_ft');
M_.endo_names = char(M_.endo_names, 'u_ft');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{u}^f');
M_.endo_names_long = char(M_.endo_names_long, 'u_ft');
M_.endo_names = char(M_.endo_names, 'w_ft');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{w}^f');
M_.endo_names_long = char(M_.endo_names_long, 'w_ft');
M_.endo_names = char(M_.endo_names, 'qk_ft');
M_.endo_names_tex = char(M_.endo_names_tex, '\hat{q}^{f,k}');
M_.endo_names_long = char(M_.endo_names_long, 'qk_ft');
M_.endo_names = char(M_.endo_names, 'outputgap_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'Output Gap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap_t');
M_.endo_names = char(M_.endo_names, 'r_ft_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_ft\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'r_ft_obs');
M_.endo_names = char(M_.endo_names, 'r_ann_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_ann\_t');
M_.endo_names_long = char(M_.endo_names_long, 'r_ann_t');
M_.endo_partitions = struct();
M_.param_names = 'psi1';
M_.param_names_tex = '\psi_1';
M_.param_names_long = 'psi1';
M_.param_names = char(M_.param_names, 'psi2');
M_.param_names_tex = char(M_.param_names_tex, '\psi_2');
M_.param_names_long = char(M_.param_names_long, 'psi2');
M_.param_names = char(M_.param_names, 'psi3');
M_.param_names_tex = char(M_.param_names_tex, '\psi_3');
M_.param_names_long = char(M_.param_names_long, 'psi3');
M_.param_names = char(M_.param_names, 'rho_r');
M_.param_names_tex = char(M_.param_names_tex, '\rho_r');
M_.param_names_long = char(M_.param_names_long, 'rho_r');
M_.param_names = char(M_.param_names, 'zeta_p');
M_.param_names_tex = char(M_.param_names_tex, '\zeta_p');
M_.param_names_long = char(M_.param_names_long, 'zeta_p');
M_.param_names = char(M_.param_names, 'iota_p');
M_.param_names_tex = char(M_.param_names_tex, '\iota_w');
M_.param_names_long = char(M_.param_names_long, 'iota_p');
M_.param_names = char(M_.param_names, 'zeta_w');
M_.param_names_tex = char(M_.param_names_tex, '\zeta_w');
M_.param_names_long = char(M_.param_names_long, 'zeta_w');
M_.param_names = char(M_.param_names, 'iota_w');
M_.param_names_tex = char(M_.param_names_tex, '\iota_w');
M_.param_names_long = char(M_.param_names_long, 'iota_w');
M_.param_names = char(M_.param_names, 'alp');
M_.param_names_tex = char(M_.param_names_tex, '\alpha');
M_.param_names_long = char(M_.param_names_long, 'alp');
M_.param_names = char(M_.param_names, 'Bigphi');
M_.param_names_tex = char(M_.param_names_tex, '\Phi');
M_.param_names_long = char(M_.param_names_long, 'Bigphi');
M_.param_names = char(M_.param_names, 'h');
M_.param_names_tex = char(M_.param_names_tex, 'h');
M_.param_names_long = char(M_.param_names_long, 'h');
M_.param_names = char(M_.param_names, 'nu_l');
M_.param_names_tex = char(M_.param_names_tex, '\nu_l');
M_.param_names_long = char(M_.param_names_long, 'nu_l');
M_.param_names = char(M_.param_names, 'rstar_aux');
M_.param_names_tex = char(M_.param_names_tex, 'rstar\_aux');
M_.param_names_long = char(M_.param_names_long, 'rstar_aux');
M_.param_names = char(M_.param_names, 'pistar_aux');
M_.param_names_tex = char(M_.param_names_tex, 'pistar\_aux');
M_.param_names_long = char(M_.param_names_long, 'pistar_aux');
M_.param_names = char(M_.param_names, 'zstar_aux');
M_.param_names_tex = char(M_.param_names_tex, 'zstar\_aux');
M_.param_names_long = char(M_.param_names_long, 'zstar_aux');
M_.param_names = char(M_.param_names, 's2');
M_.param_names_tex = char(M_.param_names_tex, 's_2');
M_.param_names_long = char(M_.param_names_long, 's2');
M_.param_names = char(M_.param_names, 'sigmac');
M_.param_names_tex = char(M_.param_names_tex, '\sigma_c');
M_.param_names_long = char(M_.param_names_long, 'sigmac');
M_.param_names = char(M_.param_names, 'ppsi');
M_.param_names_tex = char(M_.param_names_tex, 'ppsi');
M_.param_names_long = char(M_.param_names_long, 'ppsi');
M_.param_names = char(M_.param_names, 'Lmean');
M_.param_names_tex = char(M_.param_names_tex, '\bar{L}');
M_.param_names_long = char(M_.param_names_long, 'Lmean');
M_.param_names = char(M_.param_names, 'del');
M_.param_names_tex = char(M_.param_names_tex, '\delta');
M_.param_names_long = char(M_.param_names_long, 'del');
M_.param_names = char(M_.param_names, 'gstar');
M_.param_names_tex = char(M_.param_names_tex, 'g_*');
M_.param_names_long = char(M_.param_names_long, 'gstar');
M_.param_names = char(M_.param_names, 'law');
M_.param_names_tex = char(M_.param_names_tex, '\lambda_w');
M_.param_names_long = char(M_.param_names_long, 'law');
M_.param_names = char(M_.param_names, 'laf');
M_.param_names_tex = char(M_.param_names_tex, 'laf');
M_.param_names_long = char(M_.param_names_long, 'laf');
M_.param_names = char(M_.param_names, 'Fom_aux');
M_.param_names_tex = char(M_.param_names_tex, 'Fom\_aux');
M_.param_names_long = char(M_.param_names_long, 'Fom_aux');
M_.param_names = char(M_.param_names, 'epsp');
M_.param_names_tex = char(M_.param_names_tex, '\epsilon_p');
M_.param_names_long = char(M_.param_names_long, 'epsp');
M_.param_names = char(M_.param_names, 'epsw');
M_.param_names_tex = char(M_.param_names_tex, '\epsilon_w');
M_.param_names_long = char(M_.param_names_long, 'epsw');
M_.param_names = char(M_.param_names, 'rho_z');
M_.param_names_tex = char(M_.param_names_tex, '\rho_z');
M_.param_names_long = char(M_.param_names_long, 'rho_z');
M_.param_names = char(M_.param_names, 'rho_b');
M_.param_names_tex = char(M_.param_names_tex, '\rho_b');
M_.param_names_long = char(M_.param_names_long, 'rho_b');
M_.param_names = char(M_.param_names, 'rho_laf');
M_.param_names_tex = char(M_.param_names_tex, '\rho_\lambda^f');
M_.param_names_long = char(M_.param_names_long, 'rho_laf');
M_.param_names = char(M_.param_names, 'rho_law');
M_.param_names_tex = char(M_.param_names_tex, '\rho_\lambda^w');
M_.param_names_long = char(M_.param_names_long, 'rho_law');
M_.param_names = char(M_.param_names, 'rho_mu');
M_.param_names_tex = char(M_.param_names_tex, '\rho_\mu');
M_.param_names_long = char(M_.param_names_long, 'rho_mu');
M_.param_names = char(M_.param_names, 'rho_g');
M_.param_names_tex = char(M_.param_names_tex, '\rho_g');
M_.param_names_long = char(M_.param_names_long, 'rho_g');
M_.param_names = char(M_.param_names, 'eta_laf');
M_.param_names_tex = char(M_.param_names_tex, '\eta_\lambda^f');
M_.param_names_long = char(M_.param_names_long, 'eta_laf');
M_.param_names = char(M_.param_names, 'eta_law');
M_.param_names_tex = char(M_.param_names_tex, '\eta_\lambda^w');
M_.param_names_long = char(M_.param_names_long, 'eta_law');
M_.param_names = char(M_.param_names, 'eta_gz');
M_.param_names_tex = char(M_.param_names_tex, '\eta_{gz}');
M_.param_names_long = char(M_.param_names_long, 'eta_gz');
M_.param_names = char(M_.param_names, 'rho_rm');
M_.param_names_tex = char(M_.param_names_tex, '\rho_{rm}');
M_.param_names_long = char(M_.param_names_long, 'rho_rm');
M_.param_names = char(M_.param_names, 'bet');
M_.param_names_tex = char(M_.param_names_tex, '\beta');
M_.param_names_long = char(M_.param_names_long, 'bet');
M_.param_names = char(M_.param_names, 'pistar');
M_.param_names_tex = char(M_.param_names_tex, '\pi_*');
M_.param_names_long = char(M_.param_names_long, 'pistar');
M_.param_names = char(M_.param_names, 'sprd');
M_.param_names_tex = char(M_.param_names_tex, 'SPREAD_*');
M_.param_names_long = char(M_.param_names_long, 'sprd');
M_.param_names = char(M_.param_names, 'Fom');
M_.param_names_tex = char(M_.param_names_tex, 'Fom');
M_.param_names_long = char(M_.param_names_long, 'Fom');
M_.param_names = char(M_.param_names, 'zstar');
M_.param_names_tex = char(M_.param_names_tex, '\z_*');
M_.param_names_long = char(M_.param_names_long, 'zstar');
M_.param_names = char(M_.param_names, 'rstar');
M_.param_names_tex = char(M_.param_names_tex, 'r_*');
M_.param_names_long = char(M_.param_names_long, 'rstar');
M_.param_names = char(M_.param_names, 'Rstarn');
M_.param_names_tex = char(M_.param_names_tex, 'R_*');
M_.param_names_long = char(M_.param_names_long, 'Rstarn');
M_.param_names = char(M_.param_names, 'rkstar');
M_.param_names_tex = char(M_.param_names_tex, 'r^k_*');
M_.param_names_long = char(M_.param_names_long, 'rkstar');
M_.param_names = char(M_.param_names, 'omegastar');
M_.param_names_tex = char(M_.param_names_tex, 'omegastar');
M_.param_names_long = char(M_.param_names_long, 'omegastar');
M_.param_names = char(M_.param_names, 'Lstar');
M_.param_names_tex = char(M_.param_names_tex, 'L_*');
M_.param_names_long = char(M_.param_names_long, 'Lstar');
M_.param_names = char(M_.param_names, 'kstar');
M_.param_names_tex = char(M_.param_names_tex, 'k_*');
M_.param_names_long = char(M_.param_names_long, 'kstar');
M_.param_names = char(M_.param_names, 'kbarstar');
M_.param_names_tex = char(M_.param_names_tex, '\bar{k}_*');
M_.param_names_long = char(M_.param_names_long, 'kbarstar');
M_.param_names = char(M_.param_names, 'istar');
M_.param_names_tex = char(M_.param_names_tex, 'i_*');
M_.param_names_long = char(M_.param_names_long, 'istar');
M_.param_names = char(M_.param_names, 'ystar');
M_.param_names_tex = char(M_.param_names_tex, 'y_*');
M_.param_names_long = char(M_.param_names_long, 'ystar');
M_.param_names = char(M_.param_names, 'cstar');
M_.param_names_tex = char(M_.param_names_tex, 'c_*');
M_.param_names_long = char(M_.param_names_long, 'cstar');
M_.param_names = char(M_.param_names, 'wl_c');
M_.param_names_tex = char(M_.param_names_tex, 'wl_c');
M_.param_names_long = char(M_.param_names_long, 'wl_c');
M_.param_names = char(M_.param_names, 'zwstar');
M_.param_names_tex = char(M_.param_names_tex, 'i_*');
M_.param_names_long = char(M_.param_names_long, 'zwstar');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 7;
M_.endo_nbr = 43;
M_.param_nbr = 53;
M_.orig_endo_nbr = 43;
M_.aux_vars = [];
options_.varobs = cell(1);
options_.varobs(1)  = {'xgdp_q_obs'};
options_.varobs(2)  = {'hours_obs'};
options_.varobs(3)  = {'wage_obs'};
options_.varobs(4)  = {'pgdp_q_obs'};
options_.varobs(5)  = {'rff_q_obs'};
options_.varobs(6)  = {'pcer_q_obs'};
options_.varobs(7)  = {'fpi_q_obs'};
options_.varobs_id = [ 23 24 25 26 27 28 29  ];
M_.Sigma_e = zeros(7, 7);
M_.Correlation_matrix = eye(7, 7);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('US_SW07_20074_static');
erase_compiled_function('US_SW07_20074_dynamic');
M_.orig_eq_nbr = 43;
M_.eq_nbr = 43;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 1 19 0;
 2 20 62;
 3 21 63;
 0 22 0;
 4 23 0;
 0 24 64;
 0 25 0;
 5 26 65;
 6 27 0;
 0 28 66;
 0 29 0;
 7 30 67;
 0 31 0;
 0 32 68;
 0 33 69;
 8 34 0;
 9 35 0;
 10 36 0;
 11 37 0;
 12 38 0;
 13 39 0;
 14 40 0;
 0 41 0;
 0 42 0;
 0 43 0;
 0 44 0;
 0 45 0;
 0 46 0;
 0 47 0;
 15 48 0;
 16 49 70;
 17 50 71;
 0 51 0;
 18 52 0;
 0 53 72;
 0 54 0;
 0 55 73;
 0 56 0;
 0 57 0;
 0 58 74;
 0 59 0;
 0 60 0;
 0 61 0;]';
M_.nstatic = 18;
M_.nfwrd   = 7;
M_.npred   = 12;
M_.nboth   = 6;
M_.nsfwrd   = 13;
M_.nspred   = 18;
M_.ndynamic   = 25;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:7];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(43, 1);
M_.maximum_exo_lag = 1;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(7, 1);
M_.params = NaN(53, 1);
M_.NNZDerivatives = [192; 0; -1];
M_.params( 1 ) = 1.50;
psi1 = M_.params( 1 );
M_.params( 2 ) = 0.12;
psi2 = M_.params( 2 );
M_.params( 3 ) = 0.12;
psi3 = M_.params( 3 );
M_.params( 4 ) = 0.75;
rho_r = M_.params( 4 );
M_.params( 5 ) = 0.50;
zeta_p = M_.params( 5 );
M_.params( 6 ) = 0.50;
iota_p = M_.params( 6 );
M_.params( 7 ) = 0.50;
zeta_w = M_.params( 7 );
M_.params( 8 ) = 0.50;
iota_w = M_.params( 8 );
M_.params( 9 ) = 0.30;
alp = M_.params( 9 );
M_.params( 10 ) = 1.25;
Bigphi = M_.params( 10 );
M_.params( 11 ) = 0.70;
h = M_.params( 11 );
M_.params( 12 ) = 2.00;
nu_l = M_.params( 12 );
M_.params( 13 ) = 0.03;
rstar_aux = M_.params( 13 );
M_.params( 14 ) = 0.55;
pistar_aux = M_.params( 14 );
M_.params( 15 ) = 0.40;
zstar_aux = M_.params( 15 );
M_.params( 16 ) = 4.00;
s2 = M_.params( 16 );
M_.params( 17 ) = 1.50;
sigmac = M_.params( 17 );
M_.params( 18 ) = 0.50;
ppsi = M_.params( 18 );
M_.params( 19 ) = 0;
Lmean = M_.params( 19 );
M_.params( 20 ) = 0.025;
del = M_.params( 20 );
M_.params( 21 ) = 0.18;
gstar = M_.params( 21 );
M_.params( 22 ) = 1.5;
law = M_.params( 22 );
M_.params( 23 ) = 0.15;
laf = M_.params( 23 );
M_.params( 24 ) = 0.03;
Fom_aux = M_.params( 24 );
M_.params( 25 ) = 10.0;
epsp = M_.params( 25 );
M_.params( 26 ) = 10.0;
epsw = M_.params( 26 );
M_.params( 27 ) = 0.50;
rho_z = M_.params( 27 );
M_.params( 28 ) = 0.50;
rho_b = M_.params( 28 );
M_.params( 29 ) = 0.50;
rho_laf = M_.params( 29 );
M_.params( 30 ) = 0.50;
rho_law = M_.params( 30 );
M_.params( 31 ) = 0.50;
rho_mu = M_.params( 31 );
M_.params( 32 ) = 0.50;
rho_g = M_.params( 32 );
M_.params( 33 ) = 0.50;
eta_laf = M_.params( 33 );
M_.params( 34 ) = 0.50;
eta_law = M_.params( 34 );
M_.params( 35 ) = 0.50;
eta_gz = M_.params( 35 );
M_.params( 36 ) = 0.50;
rho_rm = M_.params( 36 );
steady;
oo_.dr.eigval = check(M_,options_,oo_);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 0.10;
M_.Sigma_e(2, 2) = 0.10;
M_.Sigma_e(3, 3) = 0.10;
M_.Sigma_e(4, 4) = 0.10;
M_.Sigma_e(5, 5) = 0.10;
M_.Sigma_e(6, 6) = 0.10;
M_.Sigma_e(7, 7) = 0.10;
estim_params_.var_exo = [];
estim_params_.var_endo = [];
estim_params_.corrx = [];
estim_params_.corrn = [];
estim_params_.param_vals = [];
estim_params_.param_vals = [estim_params_.param_vals; 1, 1.7985, 1.0, 3, 3, 1.5, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 4, 0.8258, 0.5, 0.975, 1, 0.75, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 2, 0.0893, 0.001, 0.5, 3, 0.125, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 3, 0.2239, 0.001, 0.5, 3, 0.125, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 5, 0.7813, 0.5, 0.95, 1, 0.5, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 7, 0.7937, 0.3, 0.95, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 8, 0.4425, 0.01, 0.99, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 6, 0.3291, 0.01, 0.99, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 9, 0.24, 0.01, 1.0, 3, 0.3, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 10, 1.4672, 1.0, 3, 3, 1.25, 0.12, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 11, 0.7205, 0.001, 0.99, 1, 0.7, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 12, 2.8401, 0.25, 10, 3, 2, 0.75, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 13, 0.7420, 0.01, 2.0, 2, 0.25, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 14, 0.7, 0.1, 2.0, 2, 0.75, 0.40, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 15, 0.3982, 0.1, 0.8, 3, 0.4, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 16, 6.3325, 2, 15, 3, 4, 1.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 17, 1.2312, 0.25, 3, 3, 1.50, 0.37, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 18, 0.2648, 0.01, 1, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 19, 1.2918, (-10.0), 10.0, 3, 0.0, 2.0, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 27, .9676, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 28, .2703, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 32, .9930, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 31, .5724, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 36, .3, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 29, .8692, .01, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 30, .9546, .001, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 33, .7652, 0.01, .9999, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 34, .8936, 0.01, .9999, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 35, 0.05, 0.01, 2.0, 3, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, 0.4618, 0.01, 3, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, 3, 0.01, 15, 4, 0.5, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, 0.1818513, 0.025, 5, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, 0.46017, 0.01, 3, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, 0.1455, 0.01, 3, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, 0.2089, 0.01, 3, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, 0.2397, 0.01, 3, 4, 0.1, 2, NaN, NaN, NaN ];
save('US_SW07_20074_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('US_SW07_20074_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('US_SW07_20074_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('US_SW07_20074_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('US_SW07_20074_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('US_SW07_20074_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('US_SW07_20074_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
