%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'US_FRBEDO08_20074';
M_.dynare_version = '4.5.7';
oo_.dynare_version = '4.5.7';
options_.dynare_version = '4.5.7';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('US_FRBEDO08_20074.log');
M_.exo_names = 'epsilonr';
M_.exo_names_tex = 'epsilonr';
M_.exo_names_long = 'epsilonr';
M_.exo_names = char(M_.exo_names, 'epsilongthetaxc');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsilongthetaxc');
M_.exo_names_long = char(M_.exo_names_long, 'epsilongthetaxc');
M_.exo_names = char(M_.exo_names, 'epsilongthetaxk');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsilongthetaxk');
M_.exo_names_long = char(M_.exo_names_long, 'epsilongthetaxk');
M_.exo_names = char(M_.exo_names, 'epsilongthetal');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsilongthetal');
M_.exo_names_long = char(M_.exo_names_long, 'epsilongthetal');
M_.exo_names = char(M_.exo_names, 'epsilonzk');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsilonzk');
M_.exo_names_long = char(M_.exo_names_long, 'epsilonzk');
M_.exo_names = char(M_.exo_names, 'epsilonzm');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsilonzm');
M_.exo_names_long = char(M_.exo_names_long, 'epsilonzm');
M_.exo_names = char(M_.exo_names, 'epsilonanr');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsilonanr');
M_.exo_names_long = char(M_.exo_names_long, 'epsilonanr');
M_.exo_names = char(M_.exo_names, 'epsilonar');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsilonar');
M_.exo_names_long = char(M_.exo_names_long, 'epsilonar');
M_.exo_names = char(M_.exo_names, 'epsilonacd');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsilonacd');
M_.exo_names_long = char(M_.exo_names_long, 'epsilonacd');
M_.exo_names = char(M_.exo_names, 'epsilonxicnnsmall');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsilonxicnnsmall');
M_.exo_names_long = char(M_.exo_names_long, 'epsilonxicnnsmall');
M_.exo_names = char(M_.exo_names, 'epsilonxicdsmall');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsilonxicdsmall');
M_.exo_names_long = char(M_.exo_names_long, 'epsilonxicdsmall');
M_.exo_names = char(M_.exo_names, 'epsilonxirsmall');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsilonxirsmall');
M_.exo_names_long = char(M_.exo_names_long, 'epsilonxirsmall');
M_.exo_names = char(M_.exo_names, 'epsilonxilsmall');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsilonxilsmall');
M_.exo_names_long = char(M_.exo_names_long, 'epsilonxilsmall');
M_.exo_names = char(M_.exo_names, 'epsilonxgf');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsilonxgf');
M_.exo_names_long = char(M_.exo_names_long, 'epsilonxgf');
M_.exo_names = char(M_.exo_names, 'eta_xgdp');
M_.exo_names_tex = char(M_.exo_names_tex, 'eta\_xgdp');
M_.exo_names_long = char(M_.exo_names_long, 'eta_xgdp');
M_.exo_names = char(M_.exo_names, 'eta_pgdp');
M_.exo_names_tex = char(M_.exo_names_tex, 'eta\_pgdp');
M_.exo_names_long = char(M_.exo_names_long, 'eta_pgdp');
M_.exo_names = char(M_.exo_names, 'eta_pecnn');
M_.exo_names_tex = char(M_.exo_names_tex, 'eta\_pecnn');
M_.exo_names_long = char(M_.exo_names_long, 'eta_pecnn');
M_.exo_names = char(M_.exo_names, 'eta_pecd');
M_.exo_names_tex = char(M_.exo_names_tex, 'eta\_pecd');
M_.exo_names_long = char(M_.exo_names_long, 'eta_pecd');
M_.exo_names = char(M_.exo_names, 'eta_per');
M_.exo_names_tex = char(M_.exo_names_tex, 'eta\_per');
M_.exo_names_long = char(M_.exo_names_long, 'eta_per');
M_.exo_names = char(M_.exo_names, 'eta_penr');
M_.exo_names_tex = char(M_.exo_names_tex, 'eta\_penr');
M_.exo_names_long = char(M_.exo_names_long, 'eta_penr');
M_.exo_names = char(M_.exo_names, 'eta_paipc');
M_.exo_names_tex = char(M_.exo_names_tex, 'eta\_paipc');
M_.exo_names_long = char(M_.exo_names_long, 'eta_paipc');
M_.exo_names = char(M_.exo_names, 'eta_paipk');
M_.exo_names_tex = char(M_.exo_names_tex, 'eta\_paipk');
M_.exo_names_long = char(M_.exo_names_long, 'eta_paipk');
M_.exo_names = char(M_.exo_names, 'eta_wage');
M_.exo_names_tex = char(M_.exo_names_tex, 'eta\_wage');
M_.exo_names_long = char(M_.exo_names_long, 'eta_wage');
M_.endo_names = 'xgdp_q_obs';
M_.endo_names_tex = 'xgdp\_q\_obs';
M_.endo_names_long = 'xgdp_q_obs';
M_.endo_names = char(M_.endo_names, 'pgdp_q_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'pgdp\_q\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'pgdp_q_obs');
M_.endo_names = char(M_.endo_names, 'rff_q_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'rff\_q\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'rff_q_obs');
M_.endo_names = char(M_.endo_names, 'pecnn_q_obs_frbedo');
M_.endo_names_tex = char(M_.endo_names_tex, 'pecnn\_q\_obs\_frbedo');
M_.endo_names_long = char(M_.endo_names_long, 'pecnn_q_obs_frbedo');
M_.endo_names = char(M_.endo_names, 'pecd_q_obs_frbedo');
M_.endo_names_tex = char(M_.endo_names_tex, 'pecd\_q\_obs\_frbedo');
M_.endo_names_long = char(M_.endo_names_long, 'pecd_q_obs_frbedo');
M_.endo_names = char(M_.endo_names, 'per_q_obs_frbedo');
M_.endo_names_tex = char(M_.endo_names_tex, 'per\_q\_obs\_frbedo');
M_.endo_names_long = char(M_.endo_names_long, 'per_q_obs_frbedo');
M_.endo_names = char(M_.endo_names, 'penr_q_obs_frbedo');
M_.endo_names_tex = char(M_.endo_names_tex, 'penr\_q\_obs\_frbedo');
M_.endo_names_long = char(M_.endo_names_long, 'penr_q_obs_frbedo');
M_.endo_names = char(M_.endo_names, 'paipc_q_obs_frbedo');
M_.endo_names_tex = char(M_.endo_names_tex, 'paipc\_q\_obs\_frbedo');
M_.endo_names_long = char(M_.endo_names_long, 'paipc_q_obs_frbedo');
M_.endo_names = char(M_.endo_names, 'paipk_q_obs_frbedo');
M_.endo_names_tex = char(M_.endo_names_tex, 'paipk\_q\_obs\_frbedo');
M_.endo_names_long = char(M_.endo_names_long, 'paipk_q_obs_frbedo');
M_.endo_names = char(M_.endo_names, 'wage_obs_frbedo');
M_.endo_names_tex = char(M_.endo_names_tex, 'wage\_obs\_frbedo');
M_.endo_names_long = char(M_.endo_names_long, 'wage_obs_frbedo');
M_.endo_names = char(M_.endo_names, 'hours_obs_frbedo');
M_.endo_names_tex = char(M_.endo_names_tex, 'hours\_obs\_frbedo');
M_.endo_names_long = char(M_.endo_names_long, 'hours_obs_frbedo');
M_.endo_names = char(M_.endo_names, 'hgdp');
M_.endo_names_tex = char(M_.endo_names_tex, 'hgdp');
M_.endo_names_long = char(M_.endo_names_long, 'hgdp');
M_.endo_names = char(M_.endo_names, 'paipgdp');
M_.endo_names_tex = char(M_.endo_names_tex, 'paipgdp');
M_.endo_names_long = char(M_.endo_names_long, 'paipgdp');
M_.endo_names = char(M_.endo_names, 'xc');
M_.endo_names_tex = char(M_.endo_names_tex, 'xc');
M_.endo_names_long = char(M_.endo_names_long, 'xc');
M_.endo_names = char(M_.endo_names, 'xk');
M_.endo_names_tex = char(M_.endo_names_tex, 'xk');
M_.endo_names_long = char(M_.endo_names_long, 'xk');
M_.endo_names = char(M_.endo_names, 'enr');
M_.endo_names_tex = char(M_.endo_names_tex, 'enr');
M_.endo_names_long = char(M_.endo_names_long, 'enr');
M_.endo_names = char(M_.endo_names, 'ecd');
M_.endo_names_tex = char(M_.endo_names_tex, 'ecd');
M_.endo_names_long = char(M_.endo_names_long, 'ecd');
M_.endo_names = char(M_.endo_names, 'er');
M_.endo_names_tex = char(M_.endo_names_tex, 'er');
M_.endo_names_long = char(M_.endo_names_long, 'er');
M_.endo_names = char(M_.endo_names, 'ecnn');
M_.endo_names_tex = char(M_.endo_names_tex, 'ecnn');
M_.endo_names_long = char(M_.endo_names_long, 'ecnn');
M_.endo_names = char(M_.endo_names, 'lambdacnn');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambdacnn');
M_.endo_names_long = char(M_.endo_names_long, 'lambdacnn');
M_.endo_names = char(M_.endo_names, 'lambdacd');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambdacd');
M_.endo_names_long = char(M_.endo_names_long, 'lambdacd');
M_.endo_names = char(M_.endo_names, 'lambdar');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambdar');
M_.endo_names_long = char(M_.endo_names_long, 'lambdar');
M_.endo_names = char(M_.endo_names, 'lambdalc');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambdalc');
M_.endo_names_long = char(M_.endo_names_long, 'lambdalc');
M_.endo_names = char(M_.endo_names, 'lambdalk');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambdalk');
M_.endo_names_long = char(M_.endo_names_long, 'lambdalk');
M_.endo_names = char(M_.endo_names, 'lc');
M_.endo_names_tex = char(M_.endo_names_tex, 'lc');
M_.endo_names_long = char(M_.endo_names_long, 'lc');
M_.endo_names = char(M_.endo_names, 'lk');
M_.endo_names_tex = char(M_.endo_names_tex, 'lk');
M_.endo_names_long = char(M_.endo_names_long, 'lk');
M_.endo_names = char(M_.endo_names, 'uc');
M_.endo_names_tex = char(M_.endo_names_tex, 'uc');
M_.endo_names_long = char(M_.endo_names_long, 'uc');
M_.endo_names = char(M_.endo_names, 'uk');
M_.endo_names_tex = char(M_.endo_names_tex, 'uk');
M_.endo_names_long = char(M_.endo_names_long, 'uk');
M_.endo_names = char(M_.endo_names, 'knrc');
M_.endo_names_tex = char(M_.endo_names_tex, 'knrc');
M_.endo_names_long = char(M_.endo_names_long, 'knrc');
M_.endo_names = char(M_.endo_names, 'knrk');
M_.endo_names_tex = char(M_.endo_names_tex, 'knrk');
M_.endo_names_long = char(M_.endo_names_long, 'knrk');
M_.endo_names = char(M_.endo_names, 'kcd');
M_.endo_names_tex = char(M_.endo_names_tex, 'kcd');
M_.endo_names_long = char(M_.endo_names_long, 'kcd');
M_.endo_names = char(M_.endo_names, 'kr');
M_.endo_names_tex = char(M_.endo_names_tex, 'kr');
M_.endo_names_long = char(M_.endo_names_long, 'kr');
M_.endo_names = char(M_.endo_names, 'xgf');
M_.endo_names_tex = char(M_.endo_names_tex, 'xgf');
M_.endo_names_long = char(M_.endo_names_long, 'xgf');
M_.endo_names = char(M_.endo_names, 'thetaxc');
M_.endo_names_tex = char(M_.endo_names_tex, 'thetaxc');
M_.endo_names_long = char(M_.endo_names_long, 'thetaxc');
M_.endo_names = char(M_.endo_names, 'thetaxk');
M_.endo_names_tex = char(M_.endo_names_tex, 'thetaxk');
M_.endo_names_long = char(M_.endo_names_long, 'thetaxk');
M_.endo_names = char(M_.endo_names, 'thetal');
M_.endo_names_tex = char(M_.endo_names_tex, 'thetal');
M_.endo_names_long = char(M_.endo_names_long, 'thetal');
M_.endo_names = char(M_.endo_names, 'gammazksmall');
M_.endo_names_tex = char(M_.endo_names_tex, 'gammazksmall');
M_.endo_names_long = char(M_.endo_names_long, 'gammazksmall');
M_.endo_names = char(M_.endo_names, 'gammazmsmall');
M_.endo_names_tex = char(M_.endo_names_tex, 'gammazmsmall');
M_.endo_names_long = char(M_.endo_names_long, 'gammazmsmall');
M_.endo_names = char(M_.endo_names, 'gammazk');
M_.endo_names_tex = char(M_.endo_names_tex, 'gammazk');
M_.endo_names_long = char(M_.endo_names_long, 'gammazk');
M_.endo_names = char(M_.endo_names, 'gammazm');
M_.endo_names_tex = char(M_.endo_names_tex, 'gammazm');
M_.endo_names_long = char(M_.endo_names_long, 'gammazm');
M_.endo_names = char(M_.endo_names, 'anr');
M_.endo_names_tex = char(M_.endo_names_tex, 'anr');
M_.endo_names_long = char(M_.endo_names_long, 'anr');
M_.endo_names = char(M_.endo_names, 'acd');
M_.endo_names_tex = char(M_.endo_names_tex, 'acd');
M_.endo_names_long = char(M_.endo_names_long, 'acd');
M_.endo_names = char(M_.endo_names, 'a_r');
M_.endo_names_tex = char(M_.endo_names_tex, 'a\_r');
M_.endo_names_long = char(M_.endo_names_long, 'a_r');
M_.endo_names = char(M_.endo_names, 'xicnn');
M_.endo_names_tex = char(M_.endo_names_tex, 'xicnn');
M_.endo_names_long = char(M_.endo_names_long, 'xicnn');
M_.endo_names = char(M_.endo_names, 'xicd');
M_.endo_names_tex = char(M_.endo_names_tex, 'xicd');
M_.endo_names_long = char(M_.endo_names_long, 'xicd');
M_.endo_names = char(M_.endo_names, 'xir');
M_.endo_names_tex = char(M_.endo_names_tex, 'xir');
M_.endo_names_long = char(M_.endo_names_long, 'xir');
M_.endo_names = char(M_.endo_names, 'xil');
M_.endo_names_tex = char(M_.endo_names_tex, 'xil');
M_.endo_names_long = char(M_.endo_names_long, 'xil');
M_.endo_names = char(M_.endo_names, 'xicnnsmall');
M_.endo_names_tex = char(M_.endo_names_tex, 'xicnnsmall');
M_.endo_names_long = char(M_.endo_names_long, 'xicnnsmall');
M_.endo_names = char(M_.endo_names, 'xicdsmall');
M_.endo_names_tex = char(M_.endo_names_tex, 'xicdsmall');
M_.endo_names_long = char(M_.endo_names_long, 'xicdsmall');
M_.endo_names = char(M_.endo_names, 'xirsmall');
M_.endo_names_tex = char(M_.endo_names_tex, 'xirsmall');
M_.endo_names_long = char(M_.endo_names_long, 'xirsmall');
M_.endo_names = char(M_.endo_names, 'xilsmall');
M_.endo_names_tex = char(M_.endo_names_tex, 'xilsmall');
M_.endo_names_long = char(M_.endo_names_long, 'xilsmall');
M_.endo_names = char(M_.endo_names, 'mcc');
M_.endo_names_tex = char(M_.endo_names_tex, 'mcc');
M_.endo_names_long = char(M_.endo_names_long, 'mcc');
M_.endo_names = char(M_.endo_names, 'mck');
M_.endo_names_tex = char(M_.endo_names_tex, 'mck');
M_.endo_names_long = char(M_.endo_names_long, 'mck');
M_.endo_names = char(M_.endo_names, 'rnrc');
M_.endo_names_tex = char(M_.endo_names_tex, 'rnrc');
M_.endo_names_long = char(M_.endo_names_long, 'rnrc');
M_.endo_names = char(M_.endo_names, 'rnrk');
M_.endo_names_tex = char(M_.endo_names_tex, 'rnrk');
M_.endo_names_long = char(M_.endo_names_long, 'rnrk');
M_.endo_names = char(M_.endo_names, 'rcd');
M_.endo_names_tex = char(M_.endo_names_tex, 'rcd');
M_.endo_names_long = char(M_.endo_names_long, 'rcd');
M_.endo_names = char(M_.endo_names, 'rr');
M_.endo_names_tex = char(M_.endo_names_tex, 'rr');
M_.endo_names_long = char(M_.endo_names_long, 'rr');
M_.endo_names = char(M_.endo_names, 'qnr');
M_.endo_names_tex = char(M_.endo_names_tex, 'qnr');
M_.endo_names_long = char(M_.endo_names_long, 'qnr');
M_.endo_names = char(M_.endo_names, 'qcd');
M_.endo_names_tex = char(M_.endo_names_tex, 'qcd');
M_.endo_names_long = char(M_.endo_names_long, 'qcd');
M_.endo_names = char(M_.endo_names, 'qr');
M_.endo_names_tex = char(M_.endo_names_tex, 'qr');
M_.endo_names_long = char(M_.endo_names_long, 'qr');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'wc');
M_.endo_names_tex = char(M_.endo_names_tex, 'wc');
M_.endo_names_long = char(M_.endo_names_long, 'wc');
M_.endo_names = char(M_.endo_names, 'wk');
M_.endo_names_tex = char(M_.endo_names_tex, 'wk');
M_.endo_names_long = char(M_.endo_names_long, 'wk');
M_.endo_names = char(M_.endo_names, 'pk');
M_.endo_names_tex = char(M_.endo_names_tex, 'pk');
M_.endo_names_long = char(M_.endo_names_long, 'pk');
M_.endo_names = char(M_.endo_names, 'paipc');
M_.endo_names_tex = char(M_.endo_names_tex, 'paipc');
M_.endo_names_long = char(M_.endo_names_long, 'paipc');
M_.endo_names = char(M_.endo_names, 'paipk');
M_.endo_names_tex = char(M_.endo_names_tex, 'paipk');
M_.endo_names_long = char(M_.endo_names_long, 'paipk');
M_.endo_names = char(M_.endo_names, 'paiwc');
M_.endo_names_tex = char(M_.endo_names_tex, 'paiwc');
M_.endo_names_long = char(M_.endo_names_long, 'paiwc');
M_.endo_names = char(M_.endo_names, 'paiwk');
M_.endo_names_tex = char(M_.endo_names_tex, 'paiwk');
M_.endo_names_long = char(M_.endo_names_long, 'paiwk');
M_.endo_names = char(M_.endo_names, 'gammaxc');
M_.endo_names_tex = char(M_.endo_names_tex, 'gammaxc');
M_.endo_names_long = char(M_.endo_names_long, 'gammaxc');
M_.endo_names = char(M_.endo_names, 'gammaxk');
M_.endo_names_tex = char(M_.endo_names_tex, 'gammaxk');
M_.endo_names_long = char(M_.endo_names_long, 'gammaxk');
M_.endo_names = char(M_.endo_names, 'kcd1');
M_.endo_names_tex = char(M_.endo_names_tex, 'kcd1');
M_.endo_names_long = char(M_.endo_names_long, 'kcd1');
M_.endo_names = char(M_.endo_names, 'kr1');
M_.endo_names_tex = char(M_.endo_names_tex, 'kr1');
M_.endo_names_long = char(M_.endo_names_long, 'kr1');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_partitions = struct();
M_.param_names = 'ALPHA';
M_.param_names_tex = 'ALPHA';
M_.param_names_long = 'ALPHA';
M_.param_names = char(M_.param_names, 'BETA');
M_.param_names_tex = char(M_.param_names_tex, 'BETA');
M_.param_names_long = char(M_.param_names_long, 'BETA');
M_.param_names = char(M_.param_names, 'CHIp');
M_.param_names_tex = char(M_.param_names_tex, 'CHIp');
M_.param_names_long = char(M_.param_names_long, 'CHIp');
M_.param_names = char(M_.param_names, 'CHIcd');
M_.param_names_tex = char(M_.param_names_tex, 'CHIcd');
M_.param_names_long = char(M_.param_names_long, 'CHIcd');
M_.param_names = char(M_.param_names, 'CHIl');
M_.param_names_tex = char(M_.param_names_tex, 'CHIl');
M_.param_names_long = char(M_.param_names_long, 'CHIl');
M_.param_names = char(M_.param_names, 'CHInr');
M_.param_names_tex = char(M_.param_names_tex, 'CHInr');
M_.param_names_long = char(M_.param_names_long, 'CHInr');
M_.param_names = char(M_.param_names, 'CHIr');
M_.param_names_tex = char(M_.param_names_tex, 'CHIr');
M_.param_names_long = char(M_.param_names_long, 'CHIr');
M_.param_names = char(M_.param_names, 'CHIw');
M_.param_names_tex = char(M_.param_names_tex, 'CHIw');
M_.param_names_long = char(M_.param_names_long, 'CHIw');
M_.param_names = char(M_.param_names, 'DELTAnr');
M_.param_names_tex = char(M_.param_names_tex, 'DELTAnr');
M_.param_names_long = char(M_.param_names_long, 'DELTAnr');
M_.param_names = char(M_.param_names, 'DELTAcd');
M_.param_names_tex = char(M_.param_names_tex, 'DELTAcd');
M_.param_names_long = char(M_.param_names_long, 'DELTAcd');
M_.param_names = char(M_.param_names, 'DELTAr');
M_.param_names_tex = char(M_.param_names_tex, 'DELTAr');
M_.param_names_long = char(M_.param_names_long, 'DELTAr');
M_.param_names = char(M_.param_names, 'ETAp');
M_.param_names_tex = char(M_.param_names_tex, 'ETAp');
M_.param_names_long = char(M_.param_names_long, 'ETAp');
M_.param_names = char(M_.param_names, 'ETAl');
M_.param_names_tex = char(M_.param_names_tex, 'ETAl');
M_.param_names_long = char(M_.param_names_long, 'ETAl');
M_.param_names = char(M_.param_names, 'ETAw');
M_.param_names_tex = char(M_.param_names_tex, 'ETAw');
M_.param_names_long = char(M_.param_names_long, 'ETAw');
M_.param_names = char(M_.param_names, 'Hcnn');
M_.param_names_tex = char(M_.param_names_tex, 'Hcnn');
M_.param_names_long = char(M_.param_names_long, 'Hcnn');
M_.param_names = char(M_.param_names, 'Hcd');
M_.param_names_tex = char(M_.param_names_tex, 'Hcd');
M_.param_names_long = char(M_.param_names_long, 'Hcd');
M_.param_names = char(M_.param_names, 'Hr');
M_.param_names_tex = char(M_.param_names_tex, 'Hr');
M_.param_names_long = char(M_.param_names_long, 'Hr');
M_.param_names = char(M_.param_names, 'KAPPA');
M_.param_names_tex = char(M_.param_names_tex, 'KAPPA');
M_.param_names_long = char(M_.param_names_long, 'KAPPA');
M_.param_names = char(M_.param_names, 'NU');
M_.param_names_tex = char(M_.param_names_tex, 'NU');
M_.param_names_long = char(M_.param_names_long, 'NU');
M_.param_names = char(M_.param_names, 'PHIr');
M_.param_names_tex = char(M_.param_names_tex, 'PHIr');
M_.param_names_long = char(M_.param_names_long, 'PHIr');
M_.param_names = char(M_.param_names, 'PHIhgdp');
M_.param_names_tex = char(M_.param_names_tex, 'PHIhgdp');
M_.param_names_long = char(M_.param_names_long, 'PHIhgdp');
M_.param_names = char(M_.param_names, 'PHIdeltahgdp');
M_.param_names_tex = char(M_.param_names_tex, 'PHIdeltahgdp');
M_.param_names_long = char(M_.param_names_long, 'PHIdeltahgdp');
M_.param_names = char(M_.param_names, 'PHIpaigdp');
M_.param_names_tex = char(M_.param_names_tex, 'PHIpaigdp');
M_.param_names_long = char(M_.param_names_long, 'PHIpaigdp');
M_.param_names = char(M_.param_names, 'PHIdeltapaigdp');
M_.param_names_tex = char(M_.param_names_tex, 'PHIdeltapaigdp');
M_.param_names_long = char(M_.param_names_long, 'PHIdeltapaigdp');
M_.param_names = char(M_.param_names, 'PSI');
M_.param_names_tex = char(M_.param_names_tex, 'PSI');
M_.param_names_long = char(M_.param_names_long, 'PSI');
M_.param_names = char(M_.param_names, 'SIGMAcnn');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAcnn');
M_.param_names_long = char(M_.param_names_long, 'SIGMAcnn');
M_.param_names = char(M_.param_names, 'SIGMAcd');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAcd');
M_.param_names_long = char(M_.param_names_long, 'SIGMAcd');
M_.param_names = char(M_.param_names, 'SIGMAr');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAr');
M_.param_names_long = char(M_.param_names_long, 'SIGMAr');
M_.param_names = char(M_.param_names, 'SIGMAl');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAl');
M_.param_names_long = char(M_.param_names_long, 'SIGMAl');
M_.param_names = char(M_.param_names, 'PAIpcstar');
M_.param_names_tex = char(M_.param_names_tex, 'PAIpcstar');
M_.param_names_long = char(M_.param_names_long, 'PAIpcstar');
M_.param_names = char(M_.param_names, 'PAIpkstar');
M_.param_names_tex = char(M_.param_names_tex, 'PAIpkstar');
M_.param_names_long = char(M_.param_names_long, 'PAIpkstar');
M_.param_names = char(M_.param_names, 'PAIwcstar');
M_.param_names_tex = char(M_.param_names_tex, 'PAIwcstar');
M_.param_names_long = char(M_.param_names_long, 'PAIwcstar');
M_.param_names = char(M_.param_names, 'PAIwkstar');
M_.param_names_tex = char(M_.param_names_tex, 'PAIwkstar');
M_.param_names_long = char(M_.param_names_long, 'PAIwkstar');
M_.param_names = char(M_.param_names, 'Pcstar');
M_.param_names_tex = char(M_.param_names_tex, 'Pcstar');
M_.param_names_long = char(M_.param_names_long, 'Pcstar');
M_.param_names = char(M_.param_names, 'Pkstar');
M_.param_names_tex = char(M_.param_names_tex, 'Pkstar');
M_.param_names_long = char(M_.param_names_long, 'Pkstar');
M_.param_names = char(M_.param_names, 'Rstar');
M_.param_names_tex = char(M_.param_names_tex, 'Rstar');
M_.param_names_long = char(M_.param_names_long, 'Rstar');
M_.param_names = char(M_.param_names, 'Xgfstar');
M_.param_names_tex = char(M_.param_names_tex, 'Xgfstar');
M_.param_names_long = char(M_.param_names_long, 'Xgfstar');
M_.param_names = char(M_.param_names, 'GAMMAzkstar');
M_.param_names_tex = char(M_.param_names_tex, 'GAMMAzkstar');
M_.param_names_long = char(M_.param_names_long, 'GAMMAzkstar');
M_.param_names = char(M_.param_names, 'GAMMAzmstar');
M_.param_names_tex = char(M_.param_names_tex, 'GAMMAzmstar');
M_.param_names_long = char(M_.param_names_long, 'GAMMAzmstar');
M_.param_names = char(M_.param_names, 'RHOanr');
M_.param_names_tex = char(M_.param_names_tex, 'RHOanr');
M_.param_names_long = char(M_.param_names_long, 'RHOanr');
M_.param_names = char(M_.param_names, 'RHOar');
M_.param_names_tex = char(M_.param_names_tex, 'RHOar');
M_.param_names_long = char(M_.param_names_long, 'RHOar');
M_.param_names = char(M_.param_names, 'RHOacd');
M_.param_names_tex = char(M_.param_names_tex, 'RHOacd');
M_.param_names_long = char(M_.param_names_long, 'RHOacd');
M_.param_names = char(M_.param_names, 'THETAxcstar');
M_.param_names_tex = char(M_.param_names_tex, 'THETAxcstar');
M_.param_names_long = char(M_.param_names_long, 'THETAxcstar');
M_.param_names = char(M_.param_names, 'THETAxkstar');
M_.param_names_tex = char(M_.param_names_tex, 'THETAxkstar');
M_.param_names_long = char(M_.param_names_long, 'THETAxkstar');
M_.param_names = char(M_.param_names, 'THETAlstar');
M_.param_names_tex = char(M_.param_names_tex, 'THETAlstar');
M_.param_names_long = char(M_.param_names_long, 'THETAlstar');
M_.param_names = char(M_.param_names, 'RHOxicnnsmall');
M_.param_names_tex = char(M_.param_names_tex, 'RHOxicnnsmall');
M_.param_names_long = char(M_.param_names_long, 'RHOxicnnsmall');
M_.param_names = char(M_.param_names, 'RHOxicdsmall');
M_.param_names_tex = char(M_.param_names_tex, 'RHOxicdsmall');
M_.param_names_long = char(M_.param_names_long, 'RHOxicdsmall');
M_.param_names = char(M_.param_names, 'RHOxirsmall');
M_.param_names_tex = char(M_.param_names_tex, 'RHOxirsmall');
M_.param_names_long = char(M_.param_names_long, 'RHOxirsmall');
M_.param_names = char(M_.param_names, 'RHOxilsmall');
M_.param_names_tex = char(M_.param_names_tex, 'RHOxilsmall');
M_.param_names_long = char(M_.param_names_long, 'RHOxilsmall');
M_.param_names = char(M_.param_names, 'RHOxgf');
M_.param_names_tex = char(M_.param_names_tex, 'RHOxgf');
M_.param_names_long = char(M_.param_names_long, 'RHOxgf');
M_.param_names = char(M_.param_names, 'RHOzm');
M_.param_names_tex = char(M_.param_names_tex, 'RHOzm');
M_.param_names_long = char(M_.param_names_long, 'RHOzm');
M_.param_names = char(M_.param_names, 'RHOzk');
M_.param_names_tex = char(M_.param_names_tex, 'RHOzk');
M_.param_names_long = char(M_.param_names_long, 'RHOzk');
M_.param_names = char(M_.param_names, 'GAMMAxkstar');
M_.param_names_tex = char(M_.param_names_tex, 'GAMMAxkstar');
M_.param_names_long = char(M_.param_names_long, 'GAMMAxkstar');
M_.param_names = char(M_.param_names, 'GAMMAxcstar');
M_.param_names_tex = char(M_.param_names_tex, 'GAMMAxcstar');
M_.param_names_long = char(M_.param_names_long, 'GAMMAxcstar');
M_.param_names = char(M_.param_names, 'Rnrcbistar');
M_.param_names_tex = char(M_.param_names_tex, 'Rnrcbistar');
M_.param_names_long = char(M_.param_names_long, 'Rnrcbistar');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 23;
M_.endo_nbr = 75;
M_.param_nbr = 55;
M_.orig_endo_nbr = 75;
M_.aux_vars = [];
options_.varobs = cell(1);
options_.varobs(1)  = {'xgdp_q_obs'};
options_.varobs(2)  = {'pgdp_q_obs'};
options_.varobs(3)  = {'rff_q_obs'};
options_.varobs(4)  = {'pecnn_q_obs_frbedo'};
options_.varobs(5)  = {'pecd_q_obs_frbedo'};
options_.varobs(6)  = {'per_q_obs_frbedo'};
options_.varobs(7)  = {'penr_q_obs_frbedo'};
options_.varobs(8)  = {'paipc_q_obs_frbedo'};
options_.varobs(9)  = {'paipk_q_obs_frbedo'};
options_.varobs(10)  = {'wage_obs_frbedo'};
options_.varobs(11)  = {'hours_obs_frbedo'};
options_.varobs_id = [ 1 2 3 4 5 6 7 8 9 10 11  ];
M_.Sigma_e = zeros(23, 23);
M_.Correlation_matrix = eye(23, 23);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 0;
erase_compiled_function('US_FRBEDO08_20074_static');
erase_compiled_function('US_FRBEDO08_20074_dynamic');
M_.orig_eq_nbr = 75;
M_.eq_nbr = 75;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 0 37 0;
 0 38 0;
 0 39 0;
 0 40 0;
 0 41 0;
 0 42 0;
 0 43 0;
 0 44 0;
 0 45 0;
 0 46 0;
 0 47 0;
 1 48 0;
 2 49 0;
 3 50 112;
 4 51 113;
 5 52 114;
 6 53 115;
 7 54 116;
 8 55 117;
 0 56 118;
 0 57 0;
 0 58 0;
 0 59 0;
 0 60 0;
 9 61 119;
 10 62 120;
 0 63 121;
 0 64 122;
 11 65 0;
 12 66 0;
 13 67 0;
 14 68 0;
 15 69 0;
 0 70 0;
 0 71 0;
 0 72 0;
 16 73 0;
 17 74 0;
 0 75 0;
 0 76 0;
 18 77 0;
 19 78 0;
 20 79 0;
 0 80 123;
 0 81 124;
 0 82 125;
 0 83 0;
 21 84 0;
 22 85 0;
 23 86 0;
 24 87 0;
 0 88 0;
 0 89 0;
 0 90 126;
 0 91 127;
 0 92 128;
 0 93 129;
 0 94 130;
 0 95 131;
 0 96 132;
 25 97 0;
 26 98 133;
 27 99 134;
 28 100 135;
 29 101 136;
 30 102 137;
 31 103 138;
 32 104 139;
 33 105 140;
 34 106 141;
 35 107 0;
 36 108 0;
 0 109 0;
 0 110 0;
 0 111 0;]';
M_.nstatic = 26;
M_.nfwrd   = 13;
M_.npred   = 19;
M_.nboth   = 17;
M_.nsfwrd   = 30;
M_.nspred   = 36;
M_.ndynamic   = 49;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:23];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(75, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(23, 1);
M_.params = NaN(55, 1);
M_.NNZDerivatives = [379; 1278; -1];
M_.params( 2 ) = 0.99;
BETA = M_.params( 2 );
M_.params( 1 ) = 0.26;
ALPHA = M_.params( 1 );
M_.params( 25 ) = 5;
PSI = M_.params( 25 );
M_.params( 9 ) = 0.03;
DELTAnr = M_.params( 9 );
M_.params( 10 ) = 0.055;
DELTAcd = M_.params( 10 );
M_.params( 11 ) = 0.0035;
DELTAr = M_.params( 11 );
M_.params( 43 ) = 7;
THETAxcstar = M_.params( 43 );
M_.params( 44 ) = 7;
THETAxkstar = M_.params( 44 );
M_.params( 45 ) = 7;
THETAlstar = M_.params( 45 );
M_.params( 39 ) = 1.003;
GAMMAzmstar = M_.params( 39 );
M_.params( 38 ) = 1.004;
GAMMAzkstar = M_.params( 38 );
M_.params( 15 ) = 0.765997735188273;
Hcnn = M_.params( 15 );
M_.params( 16 ) = 0.570758257036265;
Hcd = M_.params( 16 );
M_.params( 17 ) = 0.500499572650289;
Hr = M_.params( 17 );
M_.params( 19 ) = 1.28662724511407;
NU = M_.params( 19 );
M_.params( 3 ) = 2.33133764055832;
CHIp = M_.params( 3 );
M_.params( 12 ) = 0.257182580925403;
ETAp = M_.params( 12 );
M_.params( 8 ) = 1.55499946449095;
CHIw = M_.params( 8 );
M_.params( 14 ) = 0.295577498355445;
ETAw = M_.params( 14 );
M_.params( 6 ) = 0.831213240990633;
CHInr = M_.params( 6 );
M_.params( 4 ) = 0.144597579683815;
CHIcd = M_.params( 4 );
M_.params( 7 ) = 10.1979114360006;
CHIr = M_.params( 7 );
M_.params( 5 ) = 0.766262605233024;
CHIl = M_.params( 5 );
M_.params( 13 ) = 0.779368974304299;
ETAl = M_.params( 13 );
M_.params( 23 ) = 3.53246152082124;
PHIpaigdp = M_.params( 23 );
M_.params( 24 ) = (-0.0411799063401708);
PHIdeltapaigdp = M_.params( 24 );
M_.params( 21 ) = 0.210344028107324;
PHIhgdp = M_.params( 21 );
M_.params( 22 ) = (-0.0839315435966207);
PHIdeltahgdp = M_.params( 22 );
M_.params( 20 ) = 0.899834548353492;
PHIr = M_.params( 20 );
M_.params( 40 ) = 0.894;
RHOanr = M_.params( 40 );
M_.params( 42 ) = 0.842;
RHOacd = M_.params( 42 );
M_.params( 41 ) = 0.527;
RHOar = M_.params( 41 );
M_.params( 46 ) = 0.795;
RHOxicnnsmall = M_.params( 46 );
M_.params( 47 ) = 0.899;
RHOxicdsmall = M_.params( 47 );
M_.params( 48 ) = 0.793;
RHOxirsmall = M_.params( 48 );
M_.params( 49 ) = 0.94;
RHOxilsmall = M_.params( 49 );
M_.params( 51 ) = 0.305;
RHOzm = M_.params( 51 );
M_.params( 52 ) = 0.927;
RHOzk = M_.params( 52 );
M_.params( 50 ) = 0.982;
RHOxgf = M_.params( 50 );
M_.params( 26 ) = 1;
SIGMAcnn = M_.params( 26 );
M_.params( 27 ) = 1;
SIGMAcd = M_.params( 27 );
M_.params( 28 ) = 1;
SIGMAr = M_.params( 28 );
M_.params( 29 ) = 1;
SIGMAl = M_.params( 29 );
M_.params( 34 ) = 1;
Pcstar = M_.params( 34 );
M_.params( 35 ) = 1;
Pkstar = M_.params( 35 );
M_.params( 53 ) = M_.params(39)*M_.params(38);
GAMMAxkstar = M_.params( 53 );
M_.params( 54 ) = M_.params(39)*M_.params(38)^M_.params(1);
GAMMAxcstar = M_.params( 54 );
M_.params( 30 ) = 1.006800;
PAIpcstar = M_.params( 30 );
M_.params( 31 ) = M_.params(30)*M_.params(54)/M_.params(53);
PAIpkstar = M_.params( 31 );
M_.params( 32 ) = M_.params(30)*M_.params(54);
PAIwcstar = M_.params( 32 );
M_.params( 33 ) = M_.params(30)*M_.params(54);
PAIwkstar = M_.params( 33 );
M_.params( 36 ) = M_.params(30)*M_.params(54)*1/M_.params(2);
Rstar = M_.params( 36 );
M_.params( 55 ) = M_.params(53)*1/M_.params(2)-(1-M_.params(9));
Rnrcbistar = M_.params( 55 );
M_.params( 18 ) = M_.params(55)/M_.params(35);
KAPPA = M_.params( 18 );
M_.params( 37 ) = 0.25;
Xgfstar = M_.params( 37 );
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.param_vals = [estim_params_.param_vals; 15, 0.765997735188273, (-Inf), Inf, 1, 0.50, 0.122, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 16, 0.570758257036265, (-Inf), Inf, 1, 0.50, 0.122, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 17, 0.500499572650289, (-Inf), Inf, 1, 0.50, 0.122, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 19, 1.28662724511407, (-Inf), Inf, 2, 2.00, 1.000, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 3, 2.33133764055832, (-Inf), Inf, 2, 2.00, 1.000, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 12, 0.257182580925403, (-Inf), Inf, 1, 0.50, 0.224, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 8, 1.55499946449095, (-Inf), Inf, 2, 2.00, 1.000, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 14, 0.295577498355445, (-Inf), Inf, 1, 0.50, 0.224, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 6, 0.831213240990633, (-Inf), Inf, 2, 2.00, 1.000, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 4, 0.144597579683815, (-Inf), Inf, 2, 2.00, 1.000, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 7, 10.1979114360006, (-Inf), Inf, 2, 6.00, 1.000, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 5, 0.766262605233024, (-Inf), Inf, 2, 2.00, 1.000, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 13, 0.779368974304299, (-Inf), Inf, 1, 0.50, 0.224, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 23, 3.53246152082124, (-Inf), Inf, 3, 2.00, 1.000, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 24, (-0.0411799063401708), (-Inf), Inf, 3, 0.50, 0.400, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 21, 0.210344028107324, (-Inf), Inf, 3, 0.50, 0.400, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 22, (-0.0839315435966207), (-Inf), Inf, 3, 0.50, 0.400, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 20, 0.899834548353492, (-Inf), Inf, 1, 0.75, 0.112, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 40, 0.894, (-Inf), Inf, 1, 0.75, 0.112, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 42, 0.842, (-Inf), Inf, 1, 0.75, 0.112, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 41, 0.527, (-Inf), Inf, 1, 0.50, 0.150, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 46, 0.795, (-Inf), Inf, 1, 0.75, 0.112, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 47, 0.899, (-Inf), Inf, 1, 0.75, 0.112, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 48, 0.793, (-Inf), Inf, 1, 0.75, 0.112, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 49, 0.94, (-Inf), Inf, 1, 0.75, 0.112, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 51, 0.305, (-Inf), Inf, 1, 0.50, 0.150, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 52, 0.927, (-Inf), Inf, 1, 0.50, 0.150, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 50, 0.982, (-Inf), Inf, 1, 0.75, 0.112, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, 0.0663100954970433, (-Inf), Inf, 4, 0.040, 0.020, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 9, 0.0179503611971936, (-Inf), Inf, 4, 0.020, 0.020, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 8, 0.0816818570125166, (-Inf), Inf, 4, 0.040, 0.020, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 10, 0.0155492485707048, (-Inf), Inf, 4, 0.030, 0.020, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 11, 0.0330366121289546, (-Inf), Inf, 4, 0.030, 0.020, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 12, 0.0245289264491577, (-Inf), Inf, 4, 0.030, 0.020, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 13, 0.0217547894861637, (-Inf), Inf, 4, 0.030, 0.020, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, 0.00112204084587700, (-Inf), Inf, 4, 0.002, 0020, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, 0.00765900927066518, (-Inf), Inf, 4, 0.005, 0.020, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, 0.00293957575265040, (-Inf), Inf, 4, 0.005, 0.020, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 14, 0.0150709795689467, (-Inf), Inf, 4, 0.010, 0.02, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, 0.00526018098824289, (-Inf), Inf, 4, 0.005, 0.02, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, 0.00394143298941564, (-Inf), Inf, 4, 0.005, 0.02, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, 0.00667023414236864, (-Inf), Inf, 4, 0.005, 0.02, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 15, NaN, (-Inf), Inf, 4, 0.005, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 16, NaN, (-Inf), Inf, 4, 0.005, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 17, NaN, (-Inf), Inf, 4, 0.005, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 18, NaN, (-Inf), Inf, 4, 0.005, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 19, NaN, (-Inf), Inf, 4, 0.005, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 20, NaN, (-Inf), Inf, 4, 0.005, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 21, NaN, (-Inf), Inf, 4, 0.005, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 22, NaN, (-Inf), Inf, 4, 0.005, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 23, NaN, (-Inf), Inf, 4, 0.005, 2, NaN, NaN, NaN ];
save('US_FRBEDO08_20074_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('US_FRBEDO08_20074_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('US_FRBEDO08_20074_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('US_FRBEDO08_20074_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('US_FRBEDO08_20074_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('US_FRBEDO08_20074_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('US_FRBEDO08_20074_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
